### ISSUE TITLE
Add to list of libraries on mailhog website.

### ISSUE THREAD

**Issue by btimby** [nklsw/mailhog-python#3]
Have you thought of having your library added to:

https://github.com/mailhog/MailHog/blob/master/docs/LIBRARIES.md

Would you mind if I opened a PR there to add it? I came across that list before doing a search on PyPI and finding your library.

**Comment by nklsw** [comment]
Hi, yes I think it would make sense to have it listed there and I also opened a PR when I initially created the library: https://github.com/mailhog/MailHog/pull/429

After one year of waiting I accidentally deleted my fork and so the PR closed. Feel free to open a new PR there :)

**Comment by btimby** [comment]
Ah, I see a backlog of 32 pull requests! Probably not worth the time. I did find the library anyway.
